name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      # Reemplazar variables en index.html
      - name: Replace env variables in index.html
        run: |
          sed -i 's|\${{ env.APIKEY }}|${{ secrets.APIKEY }}|g' index.html
          sed -i 's|\${{ env.AUTH_DOMAIN }}|${{ secrets.AUTH_DOMAIN }}|g' index.html
          sed -i 's|\${{ env.URL_DATABASE }}|${{ secrets.URL_DATABASE }}|g' index.html
          sed -i 's|\${{ env.PROYET_ID }}|${{ secrets.PROYET_ID }}|g' index.html
          sed -i 's|\${{ env.STORE_BUCKET }}|${{ secrets.STORE_BUCKET }}|g' index.html
          sed -i 's|\${{ env.MESSAGING_SEND }}|${{ secrets.MESSAGING_SEND }}|g' index.html
          sed -i 's|\${{ env.APP_ID }}|${{ secrets.APP_ID }}|g' index.html
          sed -i 's|\${{ env.MEASURE }}|${{ secrets.MEASURE }}|g' index.html

      # Publicar en GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./ 